"""
Battery Intelligence Platform — Layered Decision Pipeline.

    Battery Data
        |
        v
    Engineering Rule Validation   (backend/src/classification.py)
        |
        v
    Battery Intelligence Engine   (backend/ml/ensemble_scorer.py, backend/src/risk_index.py,
        |                          backend/src/degradation_model.py, backend/ml/rul_predictor.py)
        |                          Produces, per battery:
        |                            - ML-refined Suitability Score
        |                            - Future Health (projected SoH)
        |                            - Remaining Useful Life (RUL)
        |                            - Risk Features (independent safety Risk Index)
        v
    Maintenance Recommendation    (backend/src/recommendation_engine.py)
        |
        v
    Graph Optimization            (backend/src/graph_allocator.py — Hungarian / Max-Weight Matching)
        |
        v
    Final Allocation

This module is the single place that wires the layers together. Each stage
is independently testable and independently defensible (see each module's
docstring for its engineering assumptions); this file only orchestrates them
in order and hands the fully-enriched fleet to Graph Optimization, which is
the platform's one and only final allocation engine. The Battery Intelligence
Engine (ML Suitability + Risk + RUL, generated by three internally-separate
but conceptually-unified modules) does not compete with Graph Optimization —
see backend/src/graph_allocator.py's module docstring.

`backend/src/allocators/baseline_highest_soc.py` remains the sole comparison
baseline ("Highest SoC First") so the dashboard can show judges what the
platform's layered intelligence actually buys over a naive greedy rule.
"""

from typing import Dict, Any, Optional
import pandas as pd

from backend.src.classification import classify_fleet
from backend.ml.ensemble_scorer import compute_ml_suitability_scores
from backend.src.risk_index import compute_risk_index
from backend.src.degradation_model import estimate_rul_cycles, predicted_soh_after_cycles
from backend.src.recommendation_engine import generate_recommendation
from backend.src.graph_allocator import GraphOptimizationAllocator
from backend.src.allocators.base import AllocationResult

# Labels for the consolidated pipeline stages, as surfaced by the API
# (backend/routers/metrics.py) and the frontend Method Comparison / Method
# Explainer pages. Kept in one place so the wording never drifts.
PIPELINE_STAGE_LABELS = [
    "Engineering Rule Validation",
    "Battery Intelligence Engine",
    "Maintenance Recommendation",
    "Graph Optimization (Hungarian Matching)",
    "Final Allocation",
]


def enrich_fleet(df_bat: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    Runs the Engineering Rule Validation and Battery Intelligence Engine
    stages, attaching every battery with:
      - ml_suitability_score      (ML-refined Suitability Score)
      - risk_index, risk_band     (Risk Features)
      - estimated_rul_cycles      (Remaining Useful Life)
      - predicted_future_soh      (Future Health)
      - recommended_action, maintenance_priority   (Maintenance Recommendation)
    Returns a DataFrame ready for the Graph Optimization stage.
    """
    # Stage 1: Engineering Rule Validation (tiering + rule-based Suitability Score)
    df = classify_fleet(df_bat, config)

    # Stage 2: Battery Intelligence Engine
    #   2a. ML-refined Suitability Score (enrichment signal, not an allocator)
    df["ml_suitability_score"] = compute_ml_suitability_scores(df)

    #   2b. Risk Features (independent safety Risk Index)
    risk_results = [compute_risk_index(row, config) for _, row in df.iterrows()]
    df["risk_index"] = [r["risk_index"] for r in risk_results]
    df["risk_band"] = [r["risk_band"] for r in risk_results]

    #   2c. Remaining Useful Life + Future Health
    future_cycles = config.get("battery_intelligence_platform", {}).get("future_health_projection_cycles", 50)
    df["estimated_rul_cycles"] = df.apply(lambda r: estimate_rul_cycles(r, config), axis=1)
    df["predicted_future_soh"] = df.apply(lambda r: predicted_soh_after_cycles(r, config, future_cycles), axis=1)

    # Stage 3: Maintenance Recommendation
    recommendations = [generate_recommendation(row, config, tier=row["tier"]) for _, row in df.iterrows()]
    df["recommended_action"] = [r["recommended_action"] for r in recommendations]
    df["maintenance_priority"] = [r["priority"] for r in recommendations]

    return df


def run_battery_intelligence_pipeline(
    df_bat: pd.DataFrame,
    df_veh: pd.DataFrame,
    config: Dict[str, Any],
    weight_overrides: Optional[Dict[str, float]] = None,
) -> Dict[str, Any]:
    """
    Runs the full pipeline end to end: enrichment (Engineering Rule Validation
    + Battery Intelligence Engine + Maintenance Recommendation) followed by
    Graph Optimization for the Final Allocation.

    Returns both the enriched fleet (for fleet-health/analytics endpoints)
    and the AllocationResult (assignments/unserved/KPIs). Also exposes the
    allocator's `explainability` dict (per-vehicle decision-factor breakdown
    and rejected alternatives, built by GraphOptimizationAllocator — see its
    module docstring) so callers can render the Allocation Explainability
    panel without a second pipeline run.
    """
    enriched = enrich_fleet(df_bat, config)
    allocator = GraphOptimizationAllocator(config, weight_overrides=weight_overrides)
    result: AllocationResult = allocator.allocate(enriched, df_veh)
    return {
        "enriched_fleet": enriched,
        "result": result,
        "explainability": allocator.explainability,
    }
